---  
- name: Undeploy PVC
  k8s:
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: db-namespace
    name: db-pvc
    state: absent

- name: Undeploy StorageClass Database
  k8s:
    api_version: v1
    kind: StorageClass
    namespace: default
    name: sc001
    state: absent


# - name: Delete static IP address Google Kubernetes Engine
#   gcp_compute_address:
#     name: ghost-ip-1
#     region:  us-central1
#     state: absent
#     project: "{{ gcp_project }}"
#     auth_kind: "{{ gcp_auth_kind }}"
#     service_account_file: "{{ gcp_cred_file }}"
#   #until: "cluster is not failed"
#   #delay: 60
#   #retries: 3
