---
# Playbook to undeploy Ghost and its component
# TO DO
- name: Undeploy Ghost
  hosts: localhost
  gather_facts: false
  roles:
    - { role: undeploy_ghost }
    - { role: delete_data, when: "delete_data is defined and delete_data == 'true'" }